kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  pull: default
  image: plugins/docker
  settings:
    debug: true
    registry: registry.melillo.me
    repo: registry.melillo.me/smsgw
    tags:
    - latest
    - "${DRONE_COMMIT_SHA:8}"
  environment:
    DOCKER_LAUNCH_DEBUG: true
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - pull_request
